### ISSUE TITLE
如何避免response一堆js乱码？

### ISSUE THREAD

**Issue by iaminblacklist** [hee0624/fintech_spider#1]
你好，打扰了，，作为一个爬虫小白想冒昧请教一个问题，最近在用requests获取ListContent的json内容时总是返回一堆js乱码，请问这个问题您是怎么解决的？不到一个月前我用同样的爬虫却response正常的数据，不知道问题出在哪里。

**Comment by lxw0109** [comment]
这个是因为网站在2017.6.16日（6.15日还能正常爬取）改版了， 所有的请求必须使用`Cookie`，否则得到的都是乱码。而且现在还必须使用`IP代理`，否则很容易被封（访问速度会变得特别慢，基本无法使用，改版前，输入验证码即可解封，现在似乎不行了，估计被加到黑名单里了，访问速度一直很慢）。
此外，网上有那种通过[破解URL构建的文章](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=0&rsv_idx=1&tn=baidu&wd=MmEwMD&rsv_pq=a946daa600170532&rsv_t=a2e4ZIBkHtjRBdKzRtr%2BCqvexLUQmC9%2FpIpVHdl2LweHrBMmgq%2B58afEKHw&rqlang=cn&rsv_enter=1&rsv_sug3=2&rsv_n=2)，但感觉太复杂了，所以没有细看。
因此，我现在采用的策略是先得到Cookie， 然后加上Cookie去请求就没问题了。

**Comment by iaminblacklist** [comment]
原来是这样，谢谢啦！
