### ISSUE TITLE
wenshu.court crawl question

### ISSUE THREAD

**Issue by lifuchao** [hee0624/fintech_spider#2]
你好，我用的java,最近发觉wenshu.court.gov.cn好像是升级了吧？
现在没法正常抓数据了，我看你的项目好想已经及时更新，已经能正常抓改版后的网站了是吧？我的问题是我先发httpget请求（http://wenshu.court.gov.cn/content/content?DocID={DocID}或者http://wenshu.court.gov.cn/Index/GetAllCount，你用的是前者）能拿到cookie,主要是2个参数（FSSBBIl1UgzbN7N80T和FSSBBIl1UgzbN7N80S），然后我httpost请求http://wenshu.court.gov.cn/List/ListContent，参数，header都加了的，却确始终没法正常拿到json结果。
请教下还有什么特殊的地方设置吗？
非常感谢啊

**Comment by lxw0109** [comment]
你好， 我是把得到的Cookie完整的添加到请求http://wenshu.court.gov.cn/List/ListContent的Headers中。
如果你也是这样做得但爬取不到，我觉得可能是IP的问题，请问你使用IP代理了吗？我感觉现在的IP封禁策略升级了很多， 如果IP频繁访问可能会永久被添加到黑名单中（我现在的已经被封1周了，也能访问，但速度特别特别慢，而且10次里面有8次都无法获取数据），所以我现在必须使用IP代理。
简单说就是，可能是你的IP被封了，导致无法获取到正确的json数据。（请加个IP代理试试）

**Comment by lifuchao** [comment]
@lxw0109 多谢你的回复啊，不是代理的问题。我参考你的思路改用selenium来请求http://wenshu.court.gov.cn/content/content?DocID={DocID}
然后拿到cookie(会有多个，但真正起作用的是FSSBBIl1UgzbN7N80T和FSSBBIl1UgzbN7N80S)，然后再去请求列表那个url能拿到数据了。
所以，看来还是也许还不止是cookie的问题，我发觉浏览器访问http://wenshu.court.gov.cn/content/content?DocID={DocID这个后，还加载了些其他不少的东西，具体就没细研究了，也许是还做了些什么验证。
因为用selenium会比较慢（单独这块就要5s左右），你之所以用这种方式是不是也是一开始用httpget不能正常抓数呢？不过现在没找到好的办法，就只能先这么用着了。另外，我想问下，你有试过抓文书的app吗？我用抓包工具看了下，好像信息不全，就几个请求，返回的都是加密的东西，现在还比较困惑，想搞明白用app抓是否可行？

**Comment by lxw0109** [comment]
>你之所以用这种方式是不是也是一开始用httpget不能正常抓数呢？不过现在没找到好的办法，就只能先这么用着了。

你应该也知道，其实最开始时裁判文书网不需要Cookie，就可以直接通过HTTP GET抓取到正确的数据。我最开始的数据就是这样爬取的，但由于数据量太大需要爬取的周期太长，数据还没有爬取完网站就升级了。所以，希望尽快修改现有代码，完成抓取。后来发现通过获取Cookie可以实现抓取。所以就采用了现在的方案。
这确实不是种好方法，因为爬取起来速度会很慢（必须采用多进程/多线程和IP代理）；最好的方法可能就是把cookie的构造方法找到，并自己伪造cookie，速度肯定比现有方法快。但cookie的构造方法([可以参考这里](https://www.baidu.com/s?f=8&rsv_bp=1&rsv_idx=1&word=MmEwMD&tn=91775411_hao_pg))，我觉得很麻烦，所以就没有深入研究

>另外，我想问下，你有试过抓文书的app吗？我用抓包工具看了下，好像信息不全，就几个请求，返回的都是加密的东西，现在还比较困惑，想搞明白用app抓是否可行？

对裁判文书网而言，我没有尝试通过APP进行抓取，所以不太清楚是否可以真正抓取成功，期待尝试并在此交流 : )

**Comment by lifuchao** [comment]
@lxw0109 恩，确实，想生成MmEwMD参数太费劲了。谢谢你啊，以后多交流，多跟你学习哈
