### ISSUE TITLE
求教：无法返回json

### ISSUE THREAD

**Issue by iaminblacklist** [hee0624/fintech_spider#3]
在看了您的爬取策略后，我也加上了cookie的获取，可是依然无法获取ListContent返回的json数据，冒昧请求一下，有时间的话可以帮忙看下为什么我在requests wenshu.court.gov.cn/List/ListContent的时候总是出现错误吗？(此时打开裁判文书网是正常的)

源码如下：

#获取cookie
def get_cookie():
    driver = None
    try:
        driver = webdriver.PhantomJS()
        driver.set_page_load_timeout(120)
        driver.set_script_timeout(120)

        driver.implicitly_wait(60)
        driver.get("http://wenshu.court.gov.cn/content/content?DocID=4a5c7734-fbb6-447b-a036-02191d3ee2b7")

        cookie_list = driver.get_cookies()
        print(cookie_list)
        cookie_str_list = []
        for cookie_dict in cookie_list:
            cookie_str_list.append("{0}={1};".format(cookie_dict["name"], cookie_dict["value"]))
        cookie_str = " ".join(cookie_str_list)
        print(cookie_str)
    except Exception as e:
        print("cookie!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        return ""
    else:
        return cookie_str
    finally:
        if driver:
            driver.quit()

#获取json
def doclist( page, cookie_str, Param="", Order="裁判日期"):
    if not cookie_str:
        return ""
    data = {
        'Param': '案件名称:买卖,裁判日期:' + ymd,
        'Index': page,
        'Page': "5",
        'Order': Order,
        'Direction': "asc"
    }

    headers = {
        "Host": "wenshu.court.gov.cn",
        "Referer": "http://wenshu.court.gov.cn/List/List",
        "Cookie": cookie_str,
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36',
    }

    s = requests.session()
    try:
        req = requests.Request("POST", 'http://wenshu.court.gov.cn/List/ListContent', data=data, headers=headers)
        prepped = s.prepare_request(req)
        response = s.send(prepped, timeout=60)
    except Exception as e:
        print("session!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        return ""
    else:
        print(response.text)

if __name__ == '__main__':

    ymd = '2017-01-01 TO 2017-01-02'
    num = 1

    cookie_str = get_cookie()

    docs = doclist(cookie_str, num)

**Comment by lxw0109** [comment]
你好，上面的代码没有细看，但有一点需要说明下，我用PhantomJS试过很多次，都无法爬取到，我用的是ChromeDriver

**Comment by lxw0109** [comment]
@iaminblacklist 我觉得你可以先用ChromeDriver试下   : )

**Comment by iaminblacklist** [comment]
搞定了！有一个变量写错了，，谢谢！

**Comment by lxw0109** [comment]
@iaminblacklist   使用PhantomJS能够抓取到？ 我试了很多次都没有抓取到

**Comment by iaminblacklist** [comment]
用chromedriver获取文书列表成功了，但是以文书id获取正文内容的时候就返回空白了

**Comment by chenlei1994** [comment]
最近又有新的问题了 
接口加了三个字段 vl5x':'1bb9b0b0c632e854cd8a9fe4',
                              'number':'wens',
                             'guid':'f0aba930-ca1a-537c593d-5c1811639763'
然后我加进去状态码返回200 但是response的内容是 "remind key"

**Comment by wkq278276130** [comment]
@clSpider 
这个问题你解决了吗，我也遇到这个问题了。
