### ISSUE TITLE
请教：如何获取文书正文？

### ISSUE THREAD

**Issue by iaminblacklist** [hee0624/fintech_spider#4]
你好，又来向您请教了，，我在用这个url http://wenshu.court.gov.cn/CreateContentJS/CreateContentJS.aspx?DocID=
获取文书正文页面的时候发现返回的总是空白页，参考了一下你的代码后
![image](https://user-images.githubusercontent.com/7912108/27513852-6570f32c-59a9-11e7-9566-1dcfb529ac9d.png)
依然无法正常访问，请问你是如何解决这个问题的？谢谢！

**Comment by lxw0109** [comment]
@iaminblacklist driver是 PhantomJS还是Chromedriver？PhantomJS的话我没有试成功过（全都失败了，无法抓取）

**Comment by iaminblacklist** [comment]
是用的chromedriver

**Comment by lxw0109** [comment]
这个没问题啊， 不能直接去请求[http://wenshu.court.gov.cn/CreateContentJS/CreateContentJS.aspx?DocID=](http://wenshu.court.gov.cn/CreateContentJS/CreateContentJS.aspx?DocID=)，必须得先请求[http://wenshu.court.gov.cn/content/content?DocID=](http://wenshu.court.gov.cn/content/content?DocID=), 因为还是要先得到cookie。
所以，就是代码里写的先`driver.get(self.ur_prefix + doc_id)`,然后再`driver.get(self.js_url_prefix+doc_id)`, 这样没问题， 两次get()就能得到想要的数据，**如果总是返回空白页，我觉得就是IP的问题**，我用自己的IP连续请求多次也会返回乱码或者空白页，所以才必须要求使用IP代理。建议挂上代理试试。

**Comment by iaminblacklist** [comment]
好的，我再试试，谢谢啦！

**Comment by iaminblacklist** [comment]
才注意到我后台一直运行着ccleaner，每次浏览器关闭就自动清理cookie等数据，难怪一直打不开网页，，

**Comment by lxw0109** [comment]
: )
