### ISSUE TITLE
question about selenium+chromedriver on ubuntu

### ISSUE THREAD

**Issue by lifuchao** [hee0624/fintech_spider#5]
你好，再次打扰你哈，我本地win10下测试ok了（chrome56,chromedriver2.28）.但是现在我在部署到ubuntu14.04环境下，现在主要参考http://blog.csdn.net/zhaoyabei/article/details/52355021进行了环境安装（由于我是java,所以没装python那块东西，chrome59,chromedriver2.30）,应该是安装正常了，我运行google-chrome能出来浏览器，试了搜百度正常。另外，用如下这种方式我也试了，是能正常返回的。
chromedriver -verbose

curl -d '{"desiredCapabilities":{"browser":"chrome"}}' -X POST http://127.0.0.1:9515/session --header "Content-Type:application/json"

但是我爬虫程序起来运行到这句代码new ChromeDriver()就不行了，过了估计1min吧，就报异常“org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally”，我百度谷歌都查了没找到解决办法，不知道你那边之前有没有什么特别的配置之类的？有没有遇到过类似问题，多谢了啊。

我的代码：
  String os = System.getProperties().getProperty("os.name");
                File file_chrome=null;
                if (StringUtils.startsWithIgnoreCase(os, "win")) {
                    file_chrome= new File("d:/chromedriver.exe");
                }else{
                    file_chrome= new File("/usr/bin/chromedriver");
//                    System.setProperty("webdriver.chrome.bin", "/usr/bin/google-chrome");
                }

                System.out.println(file_chrome.getAbsolutePath());
                System.setProperty("webdriver.chrome.driver", file_chrome.getAbsolutePath());
               WebDriver my_dr =new ChromeDriver();// 打开chrome浏览器

**Comment by lxw0109** [comment]
我在A电脑开发并测试完成后，部署到B电脑上运行时也遇到了`Chrome failed to start: exited abnormally`的问题（A/B两台电脑OS都一样也都是64bits，但B电脑上一直报错），所以增加了`Display`的设置(不加`Display`在B机器上跑不起来)，代码如下：
```Python
display = Display(visible=0, size=(800, 800))
display.start()
driver = webdriver.Chrome(executable_path=r"/home/lxw/Software/chromedriver_selenium/chromedriver", chrome_options=options)
```
你的Java代码我不知道是不是同样的问题， 你可以在StackOverflow上搜索一下，我的是按照[这里](https://stackoverflow.com/questions/25975241/try-to-start-chrome-driver-on-linux-with-selenium-webdriver/28187952#28187952)修改的
祝顺利~

**Comment by lxw0109** [comment]
@lifuchao  还有你可以先写一段小程序测试下chromedriver是否是好使的（先别上去就执行很长的代码，把chromedriver的部分提取出来），确保chromedriver是好使的~ 当然你可能已经这样测试过了， 只是提醒下 :）

**Comment by lifuchao** [comment]
@lxw0109 非常感谢你及时回复啊，我搜了很多，终于找到了解决办法：
nohup Xvfb :1 -screen 0 1152x900x8 &
export DISPLAY="localhost:1"

这个是关键的，除此之外还会报“[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!” 需要安装
apt-get update
apt-get install -y xorg xvfb firefox dbus-x11 xfonts-100dpi xfonts-75dpi xfonts-cyrillic

还会报错“org.openqa.selenium.WebDriverException: chrome not reachable”用户权限的问题，不能用root.
注意自己的jdk在ubuntu下是否能找到。

踩了好多坑，终于算搞定了。不过跑了几条数据发觉就又不动了，明天再看吧。谢谢你，也希望对后来人有所帮助哈

**Comment by lxw0109** [comment]
@lifuchao 👍
