### ISSUE TITLE
最近文书网站又升级了，你还能继续抓取吗？

### ISSUE THREAD

**Issue by lifuchao** [hee0624/fintech_spider#6]
应该是8.11升级的，搜索需要验证码了。
我初步看了下，现在用selenium请求doc已经拿不到关键的cookie（FSSBBIl1UgzbN7N80T和FSSBBIl1UgzbN7N80S）了，另外还多了另一个关键cookie(vjkl5)这个在js里会用来生成vl5x请求参数。
不知道你还能正常抓取吗？有没有什么好的办法？多谢了先

**Comment by sexphp** [comment]
感觉升级之后已经没法自动抓取了，每一步都需要输入验证码。

**Comment by lifuchao** [comment]
@sexphp 抓还是可以，就是慢了。变化还挺多，遇到了3种验证码，另外有几个请求参数变了
